### ISSUE TITLE
Alpine.js 3

### ISSUE THREAD

**Issue by adamkiss** [godbout/alpinejs-dash-docset#11]
There's been a new release of Alpine, Alpine 3. Do you want this docset to stay for v2, or would you accept a PR with Alpine 3?

Thank you

**Comment by godbout** [comment]
wasn't aware they had a real doc now 😅️ do you have something already? if not maybe it's easier if i start from scratch.

**Comment by godbout** [comment]
ok i'm starting it. big changes.

**Comment by godbout** [comment]
out: https://github.com/godbout/alpinejs-dash-docset/releases/tag/3.7.0

did that quick so let me know if some stuff are not working.

**Comment by godbout** [comment]
PR to Dash done: https://github.com/Kapeli/Dash-User-Contributions/pull/3522

**Comment by adamkiss** [comment]
👀
